server:
  port: 8088

spring:
  application:
    name: search-service
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${SPRING_ELASTICSEARCH_USERNAME:}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: search-group
      properties:
        spring.json.trusted.packages: "com.bookland.*"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
