server:
  port: 8087

spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:bookland}
  secret-key: ${MINIO_SECRET_KEY:bookland123}
  bucket: ${MINIO_BUCKET_NAME:bookland}

supabase:
  url: ${SUPABASE_URL}
  service-key: ${SUPABASE_KEY}
  bucket: ${SUPABASE_BUCKET}
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  propagation:
    type: w3c

logging:
  level:
    root: WARN
    com.bookland: INFO
    org.springframework: WARN
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.apache.kafka: WARN
    org.apache.zookeeper: WARN
