apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: bookland
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: bookland
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: bookland/api-gateway:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "bookland123"
            - name: IDENTITY_SERVICE_HOST
              value: "identity-service"
            - name: USER_SERVICE_HOST
              value: "user-service"
            - name: BOOK_SERVICE_HOST
              value: "book-service"
            - name: ORDER_SERVICE_HOST
              value: "order-service"
            - name: EVENT_SERVICE_HOST
              value: "event-service"
            - name: NOTIFICATION_SERVICE_HOST
              value: "notification-service"
            - name: FILE_SERVICE_HOST
              value: "file-service"
            - name: SEARCH_SERVICE_HOST
              value: "search-service"
            - name: CHAT_SERVICE_HOST
              value: "chat-service"
          ports:
            - containerPort: 8080
