apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: bookland
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: chat-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: bookland
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: bookland/chat-service:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/bookland_chat?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: USER_SERVICE_HOST
              value: "user-service"
            - name: NOTIFICATION_SERVICE_HOST
              value: "notification-service"
          ports:
            - containerPort: 8089
