apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: bookland
spec:
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: notification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: bookland
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: bookland/notification-service:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_MONGODB_URI
              value: "mongodb://root:root@mongodb:27017/notification_db?authSource=admin"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "bookland123"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
          envFrom:
            - secretRef:
                name: bookland-secret
          ports:
            - containerPort: 8086
