export const EventActionType = {
    DISCOUNT_PERCENT: 'DISCOUNT_PERCENT',
    DISCOUNT_AMOUNT: 'DISCOUNT_AMOUNT',
    DISCOUNT_FIXED_PRICE: 'DISCOUNT_FIXED_PRICE',
    FREE_SHIPPING: 'FREE_SHIPPING',
    DISCOUNT_SHIPPING_PERCENT: 'DISCOUNT_SHIPPING_PERCENT',
    DISCOUNT_SHIPPING_AMOUNT: 'DISCOUNT_SHIPPING_AMOUNT',
    FREE_GIFT: 'FREE_GIFT',
    FREE_GIFT_BY_POINT: 'FREE_GIFT_BY_POINT',
    BUY_X_GET_Y_FREE: 'BUY_X_GET_Y_FREE',
    BUY_X_GET_Y_DISCOUNT: 'BUY_X_GET_Y_DISCOUNT',
    CASHBACK_PERCENT: 'CASHBACK_PERCENT',
    CASHBACK_AMOUNT: 'CASHBACK_AMOUNT',
    GENERATE_VOUCHER: 'GENERATE_VOUCHER',
    UPGRADE_MEMBERSHIP: 'UPGRADE_MEMBERSHIP',
    BUNDLE_PRICE: 'BUNDLE_PRICE',
    TIERED_DISCOUNT: 'TIERED_DISCOUNT'
} as const;

export type EventActionType = (typeof EventActionType)[keyof typeof EventActionType];
