export const EventType = {
    FLASH_SALE: 'FLASH_SALE',
    SEASONAL_SALE: 'SEASONAL_SALE',
    CLEARANCE_SALE: 'CLEARANCE_SALE',
    BLACK_FRIDAY: 'BLACK_FRIDAY',
    CYBER_MONDAY: 'CYBER_MONDAY',
    NEW_YEAR: 'NEW_YEAR',
    BACK_TO_SCHOOL: 'BACK_TO_SCHOOL',
    BOOK_DAY: 'BOOK_DAY',
    MEMBERSHIP_EXCLUSIVE: 'MEMBERSHIP_EXCLUSIVE',
    VIP_SALE: 'VIP_SALE',
    BIRTHDAY_PROMOTION: 'BIRTHDAY_PROMOTION',
    BUY_X_GET_Y: 'BUY_X_GET_Y',
    BUNDLE_DEAL: 'BUNDLE_DEAL',
    FREE_SHIPPING: 'FREE_SHIPPING',
    VOUCHER_CODE: 'VOUCHER_CODE',
    FIRST_ORDER_DISCOUNT: 'FIRST_ORDER_DISCOUNT',
    AUTHOR_SIGNING: 'AUTHOR_SIGNING',
    NEW_RELEASE: 'NEW_RELEASE',
    PRE_ORDER: 'PRE_ORDER',
    CUSTOM: 'CUSTOM'
} as const;

export type EventType = (typeof EventType)[keyof typeof EventType];
